version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: aneterial-db
    command: ['--user=root', '--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}
    networks:
      backend:
        ipv4_address: 172.26.0.3

  nginx:
    image: nginx:1.21
    container_name: aneterial-nginx
    restart: unless-stopped
    working_dir: ${CONTAINER_WORK_PATH}
    ports:
      - ${PHP_NATIVE_PORT_EXTERNAL}:${PHP_NATIVE_PORT_INTERNAL}
      - ${PHP_LARAVEL_PORT_EXTERNAL}:${PHP_LARAVEL_PORT_INTERNAL}
    volumes:
      - ${NGINX_SETTINGS_HOST}:${NGINX_SETTINGS_CONTAINER}
      - ${NGINX_LOGS_HOST}:${NGINX_LOGS_CONTAINER}
      - ${PHP_NATIVE_PATH}:${PHP_NATIVE_CONTAINER}
      - ${PHP_LARAVEL_PATH}:${PHP_LARAVEL_CONTAINER}
    environment:
      NGINX_LOGS_CONTAINER: "${NGINX_LOGS_CONTAINER}"

      PHP_NATIVE_PORT_INTERNAL: "${PHP_NATIVE_PORT_INTERNAL}"
      PHP_NATIVE_CONTAINER: "${PHP_NATIVE_CONTAINER}"
      PHP_NATIVE_FPM_PORT: "${PHP_NATIVE_FPM_PORT}"

      PHP_LARAVEL_PORT_INTERNAL: "${PHP_LARAVEL_PORT_INTERNAL}"
      PHP_LARAVEL_CONTAINER: "${PHP_LARAVEL_CONTAINER}"
      PHP_LARAVEL_FPM_PORT: "${PHP_LARAVEL_FPM_PORT}"
    networks:
      backend:
        ipv4_address: 172.26.0.4

  php-native-app:
    build:
      context: ${PHP_NATIVE_PATH}/docker/php
      dockerfile: Dockerfile
      args:
        PORT: ${PHP_NATIVE_FPM_PORT}
        DIR: ${PHP_NATIVE_CONTAINER}
    image: aneterial-${PHP_NATIVE}
    container_name: aneterial-${PHP_NATIVE}
    restart: always
    volumes:
      - ${PHP_NATIVE_PATH}:${PHP_NATIVE_CONTAINER}
      - ${PHP_NATIVE_INI_HOST}:${PHP_NATIVE_INI_CONTAINER}
    working_dir: ${PHP_NATIVE_CONTAINER}
    hostname: localhost'
    networks:
      backend:
        ipv4_address: 172.26.0.5

  php-laravel-app:
    build:
      context: ${PHP_LARAVEL_PATH}/docker/php
      dockerfile: Dockerfile
      args:
        PORT: ${PHP_LARAVEL_FPM_PORT}
        DIR: ${PHP_LARAVEL_CONTAINER}
    image: aneterial-${PHP_LARAVEL}
    container_name: aneterial-${PHP_LARAVEL}
    restart: always
    volumes:
      - ${PHP_LARAVEL_PATH}:${PHP_LARAVEL_CONTAINER}
      - ${PHP_LARAVEL_INI_HOST}:${PHP_LARAVEL_INI_CONTAINER}
    working_dir: ${PHP_LARAVEL_CONTAINER}
    hostname: localhost'
    networks:
      backend:
        ipv4_address: 172.26.0.6

networks:
  backend:
    name: aneterial-backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
